"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: 
  IDL file: quest_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types


@dataclass
@annotate.final
@annotate.autoid("sequential")
class VRPose(idl.IdlStruct, typename="VRPose"):
    hmd_q: types.array[types.float32, 4]
    hmd_t: types.array[types.float32, 3]
    left_q: types.array[types.float32, 4]
    left_t: types.array[types.float32, 3]
    right_q: types.array[types.float32, 4]
    right_t: types.array[types.float32, 3]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Pose6D(idl.IdlStruct, typename="Pose6D"):
    orientation: types.array[types.float32, 4]
    translation: types.array[types.float32, 3]